- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  switches:
    tv_toshiba:
      friendly_name: TV
      command_on: JgBYAAABJ5EUERMRExMSEhMTFBATNhMSEzcUNRQ0EzcSNhM2FBITNRQRFDUUERMTEjYTERUQFhESNRYQFDYSNhMSEzUUNhQ1FAAFEwABKEgUAAw7AAEmSRQADQU=
      command_off: JgBYAAABJ5EUERMRExMSEhMTFBATNhMSEzcUNRQ0EzcSNhM2FBITNRQRFDUUERMTEjYTERUQFhESNRYQFDYSNhMSEzUUNhQ1FAAFEwABKEgUAAw7AAEmSRQADQU=
#    magic_light_6w:
#      friendly_name: 'Corner Light'
#      command_on: JgBQAAABKZIUERMTEhMSEhMSEhUREhQSEjYUOBI2EzcVNhM4ETcUNxM2FDYTOBMSFBESExMTExIRExISExMSNxQ2EzcUNxM2EwAFIgABJkoTAA0FAAAAAAAAAAA=
#      command_off: JgBQAAABKZMTERQRExMUERMRFRISERUQFDYUNhM4EzYUNhM3EzcUNxISEzcTOBITEhITFBEUERMSOBMRFBETNxM4EjcSNxU3EgAFIAABKEoUAA0FAAAAAAAAAAA=
    topbox_key_2:
      friendly_name: 'Topbox 2'
      command_on: JgBYAAABK5QVEBUQFBEVEhMTEhEUEhMSFTYTNxQ2FDcUNhQ3FBEVNRURExIVERMSEzcUEhQ3ExEUNxQ3EzgSNxUQFDgTEhQ3FAAFNAABKkoUAAxTAAEqSRQADQU=
      command_off: JgBYAAABK5QVEBUQFBEVEhMTEhEUEhMSFTYTNxQ2FDcUNhQ3FBEVNRURExIVERMSEzcUEhQ3ExEUNxQ3EzgSNxUQFDgTEhQ3FAAFNAABKkoUAAxTAAEqSRQADQU=
    topbox_key_3:
      friendly_name: 'Topbox 3'
      command_on: JgBQAAABK5MUExITExMTEBURExIUERUREzgTNxQ2FTcSNxU2ExITNxQRFREUEhQRFDYTEhURFBIUNRU2EzcUNxMSFDYUNxM4EwAFNQABK0kVAA0FAAAAAAAAAAA=
      command_off: JgBQAAABK5MUExITExMTEBURExIUERUREzgTNxQ2FTcSNxU2ExITNxQRFREUEhQRFDYTEhURFBIUNRU2EzcUNxMSFDYUNxM4EwAFNQABK0kVAA0FAAAAAAAAAAA=
    topbox_key_ok:
      friendly_name: 'Topbox OK'
      command_on: JgBQAAABK5IUEhQRFBEUEhMSFBEUExISFTcSNxQ2FDgSNxQ3ExIUNxMSEzcVEBQ4EzYVEBQSExMUNxISFDYVERQREzkTNxI3FQAFNAABLEgUAA0FAAAAAAAAAAA=
      command_off: JgBQAAABK5IUEhQRFBEUEhMSFBEUExISFTcSNxQ2FDgSNxQ3ExIUNxMSEzcVEBQ4EzYVEBQSExMUNxISFDYVERQREzkTNxI3FQAFNAABLEgUAA0FAAAAAAAAAAA=
    hdmi_switch_1:
      friendly_name: 'Kodi'
      command_on: JgBQAAABJ5MVExMSExURFBMTExMTFBI2FTUUNxM2FTUTOBQ1EzgSFBI4FBITNhQTExQTExIVERQSFRE3ExURNxU0FTYTNhQ2FAAFHwABKEkTAA0FAAAAAAAAAAA=
      command_off: JgBQAAABJ5MVExMSExURFBMTExMTFBI2FTUUNxM2FTUTOBQ1EzgSFBI4FBITNhQTExQTExIVERQSFRE3ExURNxU0FTYTNhQ2FAAFHwABKEkTAA0FAAAAAAAAAAA=
    hdmi_switch_3:
      friendly_name: 'Android'
      command_on: JgBQAAABJ5USExMUFBEUExMSFBIUEhQ3EzcUNRQ2FDcSOBM1FDYVEhQSExQSExU2ExITExURFBIUNxQ1FTUUExI3FTUTOBI2FgAFHAABJ0kVAA0FAAAAAAAAAAA=
      command_off: JgBQAAABJ5USExMUFBEUExMSFBIUEhQ3EzcUNRQ2FDcSOBM1FDYVEhQSExQSExU2ExITExURFBIUNxQ1FTUUExI3FTUTOBI2FgAFHAABJ0kVAA0FAAAAAAAAAAA=
    hdmi_switch_5:
      friendly_name: 'Live TV'
      command_on: JgBQAAABKJUSExQTFBITEhQUEhQSEhU1FjUTNhQ2FDYUNhQ2FTYSFBQ1FTUTExM3FDYTExMTFREUExQSEzYTExQSFTUUNhU1FAAFHQABJ0oVAA0FAAAAAAAAAAA=
      command_off: JgBQAAABKJUSExQTFBITEhQUEhQSEhU1FjUTNhQ2FDYUNhQ2FTYSFBQ1FTUTExM3FDYTExMTFREUExQSEzYTExQSFTUUNhU1FAAFHQABJ0oVAA0FAAAAAAAAAAA=
