- platform: broadlink
  host: !secret broadlink_mini_host
  mac: !secret broadlink_mini_mac
  switches:
     air_conditioner:
       friendly_name: 'Air Conditioner'
       command_on: JgBEAAABHYQQMhEQEREQERExEREQEhAQERIPERATDhIQEg8REBEQEREyEBIPEhAyEBEQEg8TDxIPMRETDxEQMhEAC30OAA0FAAAAAA==
       command_off: JgBAAAABHYUQMhIPEBERERAyERERDxIQEDIRMRESEBAREBIQEBIPERASEBEREBEREBARMhATDzEQEhAREREQMxAADQUAAAAAAAAAAA== 
#    magic_light_6w:
#      friendly_name: 'Corner Light'
#      command_on: JgBQAAABKZIUERMTEhMSEhMSEhUREhQSEjYUOBI2EzcVNhM4ETcUNxM2FDYTOBMSFBESExMTExIRExISExMSNxQ2EzcUNxM2EwAFIgABJkoTAA0FAAAAAAAAAAA=
#      command_off: JgBQAAABKZMTERQRExMUERMRFRISERUQFDYUNhM4EzYUNhM3EzcUNxISEzcTOBITEhITFBEUERMSOBMRFBETNxM4EjcSNxU3EgAFIAABKEoUAA0FAAAAAAAAAAA=
