- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  switches:
    tv_toshiba:
      friendly_name: TV
      command_on: JgBYAAABJ5EUERMRExMSEhMTFBATNhMSEzcUNRQ0EzcSNhM2FBITNRQRFDUUERMTEjYTERUQFhESNRYQFDYSNhMSEzUUNhQ1FAAFEwABKEgUAAw7AAEmSRQADQU=
      command_off: JgBYAAABJ5EUERMRExMSEhMTFBATNhMSEzcUNRQ0EzcSNhM2FBITNRQRFDUUERMTEjYTERUQFhESNRYQFDYSNhMSEzUUNhQ1FAAFEwABKEgUAAw7AAEmSRQADQU=
#    magic_light_6w:
#      friendly_name: 'Corner Light'
#      command_on: JgBQAAABKZIUERMTEhMSEhMSEhUREhQSEjYUOBI2EzcVNhM4ETcUNxM2FDYTOBMSFBESExMTExIRExISExMSNxQ2EzcUNxM2EwAFIgABJkoTAA0FAAAAAAAAAAA=
#      command_off: JgBQAAABKZMTERQRExMUERMRFRISERUQFDYUNhM4EzYUNhM3EzcUNxISEzcTOBITEhITFBEUERMSOBMRFBETNxM4EjcSNxU3EgAFIAABKEoUAA0FAAAAAAAAAAA=
#    topbox_key_2:
#      friendly_name: 'Topbox 2'
#      command_on: JgBYAAABK5QVEBUQFBEVEhMTEhEUEhMSFTYTNxQ2FDcUNhQ3FBEVNRURExIVERMSEzcUEhQ3ExEUNxQ3EzgSNxUQFDgTEhQ3FAAFNAABKkoUAAxTAAEqSRQADQU=
#      command_off: JgBYAAABK5QVEBUQFBEVEhMTEhEUEhMSFTYTNxQ2FDcUNhQ3FBEVNRURExIVERMSEzcUEhQ3ExEUNxQ3EzgSNxUQFDgTEhQ3FAAFNAABKkoUAAxTAAEqSRQADQU=
#    topbox_key_3:
#      friendly_name: 'Topbox 3'
#      command_on: JgBQAAABK5MUExITExMTEBURExIUERUREzgTNxQ2FTcSNxU2ExITNxQRFREUEhQRFDYTEhURFBIUNRU2EzcUNxMSFDYUNxM4EwAFNQABK0kVAA0FAAAAAAAAAAA=
#      command_off: JgBQAAABK5MUExITExMTEBURExIUERUREzgTNxQ2FTcSNxU2ExITNxQRFREUEhQRFDYTEhURFBIUNRU2EzcUNxMSFDYUNxM4EwAFNQABK0kVAA0FAAAAAAAAAAA=
#    topbox_key_ok:
#      friendly_name: 'Topbox OK'
#      command_on: JgBQAAABK5IUEhQRFBEUEhMSFBEUExISFTcSNxQ2FDgSNxQ3ExIUNxMSEzcVEBQ4EzYVEBQSExMUNxISFDYVERQREzkTNxI3FQAFNAABLEgUAA0FAAAAAAAAAAA=
#      command_off: JgBQAAABK5IUEhQRFBEUEhMSFBEUExISFTcSNxQ2FDgSNxQ3ExIUNxMSEzcVEBQ4EzYVEBQSExMUNxISFDYVERQREzkTNxI3FQAFNAABLEgUAA0FAAAAAAAAAAA=
    live_tv:
      friendly_name: "Live TV"
      command_on: JgBYAAABKJAUExQRFBEUEhQRFBETExM3EjcUNhQ2FDYTNxQ2FDYTEhQSEzcUEhQQFDYUExIUEhMSNhURFDYUNhQRFDgTNxI2FAAFHQABKUkUAAxZAAEoSxIADQU=
      command_off: JgBYAAABKJAUExQRFBEUEhQRFBETExM3EjcUNhQ2FDYTNxQ2FDYTEhQSEzcUEhQQFDYUExIUEhMSNhURFDYUNhQRFDgTNxI2FAAFHQABKUkUAAxZAAEoSxIADQU=
    kodi:
      friendly_name: "Kodi"
      command_on: JgBQAAABJ5ITFBITEhQRFBITExETExM3EzcTNxM2FDcTNhQ3EzYUEhMTEzYTNxQ3EzgSEhQSExITNxMTEhMSExMSEzcTOBM3EwAFHQABKUkTAA0FAAAAAAAAAAA=
      command_off: JgBQAAABJ5ITFBITEhQRFBITExETExM3EzcTNxM2FDcTNhQ3EzYUEhMTEzYTNxQ3EzgSEhQSExITNxMTEhMSExMSEzcTOBM3EwAFHQABKUkTAA0FAAAAAAAAAAA=

    amazon_firetv:
      friendly_name: "Amazon Fire TV"
      command_on: JgBQAAABKZEUERURFBEWEBUQFBEUEhQ2FDYTNhU1FjQVNRY1FDUVEhQQFBEVNRUQFhAWEBUPFw8VNhQ1FRAWNBY0FTYUNRU1FgAFGwABKkkUAA0FAAAAAAAAAAA=
      command_off: JgBQAAABKZEUERURFBEWEBUQFBEUEhQ2FDYTNhU1FjQVNRY1FDUVEhQQFBEVNRUQFhAWEBUPFw8VNhQ1FRAWNBY0FTYUNRU1FgAFGwABKkkUAA0FAAAAAAAAAAA=

    chromecast_living_room:
      command_on: JgBMAAABKJEUEhMSFBEUERUSEhMUERM3FDUUNxQ1FDYUNhQ2FTYTEhMTEzYUNhURFBEVERMUERQTNRMSFBIUNhM2FDYUNhU1FAAFHkAADQUAAAAAAAAAAAAAAAA=
      command_off: JgBMAAABKJEUEhMSFBEUERUSEhMUERM3FDUUNxQ1FDYUNhQ2FTYTEhMTEzYUNhURFBEVERMUERQTNRMSFBIUNhM2FDYUNhU1FAAFHkAADQUAAAAAAAAAAAAAAAA=

    samsung_sb:
      friendly_name: "Samsung Soundbar"
      command_on: JgCgAJaSEhEQERAPExASLhMxEQ8TDxEwEjASMBIwEw4TDhIPEw8RkxIPEg8SEBEPEg8SDxMOFA0SMBMvEy8SEBIvEzATMBIvEQ8SEBMNEy8TAAcflpMSEBAREQ8SDxIwEy8SDxIPEjATLxIwEy8TDxIPEg8SDhKUERARDxIPEg8TDhIREBAREBIvEjATLxMOEy8TMBIwEjERDxIPEg8SMBIADQUAAAAAAAAAAA==
      command_off: JgCgAJWTEg8SDxIPEg8SMRMuEhATDhEwEjIQMRIvFA4TDhIQEQ8TkhEPEg8SDxIREQ4UDRIPFA0TMREwEjATDhMvEjATMBEwEw4SEBEPEjERAAcglpISERIOEg4SDxExEy8UDhEREDASMhEvEzASDxIQEQ8TDxKREhAREBEPEg8TDxMOEREREBIvETESMREQETASMBMvEjIREBAPEw4SMRIADQUAAAAAAAAAAA==

    samsung_sb_source:
      friendly_name: "Samsung SB Source"
      command_on: JgCgAJWUERAQDxQNEhARMBMwEw4SDxExEjEQMRIwEhARDxMOEg8SkxIPEg8SEBEPEjASEBIvEw8SLxIwEjASDxMPETASEBExEg4TDhIPEjESAAcflpMRDxMPERASDxMvETIRDxMOEy8SMBIwEjAUDRMOEw4SDxOSEhARDxMOEg8SMBIPEjETDRIxETASMhEOEw8SMREPEjATDhIQEg4SMREADQUAAAAAAAAAAA==
      command_off: JgCgAJWUERAQDxQNEhARMBMwEw4SDxExEjEQMRIwEhARDxMOEg8SkxIPEg8SEBEPEjASEBIvEw8SLxIwEjASDxMPETASEBExEg4TDhIPEjESAAcflpMRDxMPERASDxMvETIRDxMOEy8SMBIwEjAUDRMOEw4SDxOSEhARDxMOEg8SMBIPEjETDRIxETASMhEOEw8SMREPEjATDhIQEg4SMREADQUAAAAAAAAAAA==
