- platform: template
  switches:
    living_room_lights:
      value_template: "{{ is_state('sensor.livingroom_lights_state', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.living_room_lights_on
      turn_off:
        service: script.turn_on
        entity_id: script.living_room_lights_off

    livingroom_tv:
      value_template: "{{ is_state('sensor.livingroom_tv_state', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.livingroom_tv_on
      turn_off:
        service: script.turn_on
        entity_id: script.livingroom_tv_off
