alias: 'Mosquitto Status'
trigger:
  platform: template
  value_template: "{% if is_state('binary_sensor.mosquitto', 'off') %}true{% endif %}"
action:
  service: notify.ronen_pushbullet
  data:
    title: "Process - Warning"
    message: "Mosquitto is not running"

