alias: 'iOmega wraning - above 90'
trigger:
  platform: template
  value_template: "{% if states('sensor.disk_used_mntiomega') | float > 89.9  %}true{% endif %}"
action:
  service: notify.ronen_pushbullet
  data:
    title: "iOmega - Warning"
    message: "Disk usage on iOmega is above 90%"
