homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 767
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  customize: !include_dir_merge_named customize

map:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes:
    azure:
      primary-color: azure
    pink:
      primary-color: pink
    blue:
      primary-color: blue
    darkred:
      primary-color: darkred


http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Check for config:
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google

#datadog:

ffmpeg:
#  ffmpeg_bin: /usr/bin/avconv
  ffmpeg_bin: /usr/bin/ffmpeg

#camera:
#  - platform: onvif
#    host: !secret camera_input
#    name: 'Kids Room'
#    port: 554
#  - platform: ffmpeg
#    input: !secret camera_input
#    name: 'Kids Room'
#    extra_arguments: -q:v 2
#  - platform: yi
#    name: "Living Room"
#    host: !secret yi_camera_host
#    password: !secret yi_camera_password
#    extra_arguments: '-vf scale=800:450'
  
#logger:
#  default: warning
#  logs:
#    homeassistant.components.camera.ffmpeg: debug

media_player:
#  - platform: kodi
#    name: OSMC
#    host: !secret media_player_host_osmc
#    username: !secret media_player_username_osmc
#    password: !secret media_player_password_osmc
  - platform: kodi
    name: BeeLink
    host: !secret media_player_host_beelink
    username: !secret media_player_username_beelink
    password: !secret media_player_password_beelink
  - platform: spotify
    name: Spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
#  - platform: firetv
  - platform: cast

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  type: alexa
  listen_port: 8300
  expose_by_default: false

google_assistant:
  project_id: !secret google_project_id
  client_id: !secret google_client_id
  access_token: !secret google_access_token
  agent_user_id: !secret google_agent_user_id
  api_key: !secret google_api_key
  exposed_domains:
    - switch

alert: !include_dir_merge_list alerts
automation: !include_dir_list automations
binary_sensor: !include_dir_merge_list binary_sensors
device_tracker: !include_dir_merge_list trackers
group: !include_dir_merge_named group
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
#light: !include lights.yaml
mqtt: !include servers/mqtt.yaml
notify: !include_dir_merge_list notifiers
#panel_iframe: !include_dir_named iframes
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
shell_command: !include commands/shell_commands.yaml
switch: !include_dir_merge_list switches/
zone: !include_dir_merge_list zones


