alias: 'iOmega Status'
trigger:
  platform: template
  value_template: "{% if is_state('binary_sensor.iomega', 'off') %}true{% endif %}"
action:
  service: notify.ronen_pushbullet
  data:
    title: "Server - Warning"
    message: "iOmega is down"

