alias: 'OSMC Status'
trigger:
  platform: template
  value_template: "{% if is_state('binary_sensor.osmc_server', 'off') %}true{% endif %}"
action:
  service: notify.ronen_pushbullet
  data:
    title: "Server - Warning"
    message: "OSMC is down"

