alias: 'Front Door Sensor Status'
trigger:
  - platform: template
    value_template: "{% if is_state('binary_sensor.front_door_sensor', 'on') %}true{% endif %}"
action:
  - service: camera.snapshot
    data:
      entity_id: camera.living_room
      filename: "/mnt/iomega/hass/snapshots/camera.living_room.jpg"
  - service: notify.ronen_pushbullet
    data:
      title: "Motion Detect"
      message: "Front door got opened"
      data:
        file: "/mnt/iomega/hass/snapshots/camera.living_room.jpg"
