alias: 'Kids Room Window Status'
trigger:
  platform: template
  value_template: "{% if is_state('binary_sensor.kids_room_window', 'on') %}true{% endif %}"
action:
  service: notify.ronen_pushbullet
  data:
    title: "Motion Detect"
    message: "Kids room window got opened"

