alias: 'Living Room Motion Sensor Status'
trigger:
  platform: template
  value_template: "{% if is_state('binary_sensor.living_room_motion_sensor', 'on') %}true{% endif %}"
condition:
  condition: time
  after: '09:00'
  before: '16:30'
  weekday:
   - sun
   - mon
   - tue
   - wed
   - thu
action:
  service: notify.ronen_pushbullet
  data:
    title: "Motion Detect"
    message: "Got motion in the living room"

