alias: 'Porch Door Sensor Status'
trigger:
  platform: template
  value_template: "{% if is_state('binary_sensor.porch_door_sensor', 'on') %}true{% endif %}"
action:
  service: notify.ronen_pushbullet
  data:
    title: "Motion Detect"
    message: "Porch door got opened"

