alias: 'Turn off boiler after 1 hour'
trigger:
  - platform: state
    entity_id: switch.boiler_switch
    from: 'off'
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
action:
  - service: switch.turn_off
    entity_id: switch.boiler_switch
