alias: 'Turn off all lights'
trigger:
  - platform: state
    entity_id: 'switch.all_lights_off'
    from: 'off'
    to: 'on'
action:
  - service: script.turn_on
    entity_id: script.turn_off_all_lights
  - service: switch.turn_off
    entity_id: switch.all_lights_off
