motion_switches_on:
  sequence:
    - service: automation.turn_on
      entity_id: automation.front_door_sensor_status
    - service: automation.turn_on
      entity_id: automation.porch_door_sensor_status
    - service: automation.turn_on
      entity_id: automation.living_room_motion_sensor_status

motion_switches_off:
  sequence:
    - service: automation.turn_off
      entity_id: automation.front_door_sensor_status
    - service: automation.turn_off
      entity_id: automation.porch_door_sensor_status
    - service: automation.turn_off
      entity_id: automation.living_room_motion_sensor_status


