- platform: darksky
  api_key: !secret dark_sky_api_key
  update_interval: 300
  monitored_conditions:
     - summary
     - icon
     - nearest_storm_distance
     - precip_type
     - precip_intensity
     - precip_probability
     - temperature
     - apparent_temperature
     - dew_point
     - wind_speed
     - wind_bearing
     - cloud_cover
     - humidity
     - pressure
     - visibility
     - ozone
     - minutely_summary
     - hourly_summary
     - daily_summary

