- platform: google_travel_time
  name: "Ronen's Work"
  api_key: !secret google_travel_time_api_key
  #origin: place_id:ChIJK2m-AvvJAhURiHo8ebkicHs
  #destination: place_id:ChIJJ4yJVCrLAhURzKxGlW1uudU
  origin: zone.home
  destination: zone.ronen_work

- platform: google_travel_time
  name: "Ronen's Home"
  api_key: !secret google_travel_time_api_key
  origin: zone.ronen_work
  destination: zone.home

- platform: google_travel_time
  name: "Michal's Work"
  api_key: !secret google_travel_time_api_key
  origin: zone.home
  destination: zone.michal_work

- platform: google_travel_time
  name: "Michal's Home"
  api_key: !secret google_travel_time_api_key
  origin: zone.michal_work
  destination: zone.home
