- platform: template
  sensors:
    livingroom_lights_state:
      value_template: "{% if is_state('switch.livingroom_1_light', 'on') and is_state('switch.livingroom_2_light', 'on') %}on{% else %}off{% endif %}"
      friendly_name: 'Livingroom Lights State'
