- platform: template
  sensors:
    livingroom_tv_state:
      value_template: "{% if is_state('switch.tv_toshiba', 'on') and is_state('switch.samsung_sb', 'on') %}on{% else %}off{% endif %}"
      friendly_name: 'Livingroom TV State'
