- platform: transmission
  host: !secret transmission_host
  port: 9091
  username: !secret transmission_username
  password: !secret transmission_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
